# Generated by Django 5.0.6 on 2024-07-23 07:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Databolge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katmandegeri', models.IntegerField(blank=True, null=True)),
                ('bolgeadi', models.CharField(blank=True, max_length=250, null=True)),
                ('koordinat', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'databolge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datayol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yoltipi', models.IntegerField(blank=True, null=True)),
                ('yolhizlimiti', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('uzunluk', models.DecimalField(decimal_places=5, max_digits=15)),
                ('koordinat', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('yoladi', models.CharField(blank=True, max_length=250, null=True)),
                ('yolbolge', models.CharField(blank=True, max_length=250, null=True)),
                ('merkezlat', models.FloatField(blank=True, null=True)),
                ('merkezlong', models.FloatField(blank=True, null=True)),
                ('yoltamadres', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'datayol',
                'managed': False,
            },
        ),
    ]
